version: '2.4'

services:
  postgres:
    env_file:
      - '.env'
    image: 'postgres:11.5-alpine'
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    ports:
      - '${DOCKER_POSTGRES_PORT:-127.0.0.1:5432}:5432'
    stop_grace_period: '${DOCKER_STOP_GRACE_PERIOD:-3s}'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  web:
    env_file:
      - '.env'
    build: .
    depends_on:
      - 'postgres'
    ports:
     - '${DOCKER_WEB_PORT:-127.0.0.1:8000}:8000'
    stop_grace_period: '${DOCKER_STOP_GRACE_PERIOD:-3s}'
    volumes:
      - '${DOCKER_WEB_VOLUME:-./public:/app/public}'

volumes:
  postgres: {}